#!/bin/bash
# Example training commands demonstrating flexible stage training
# This script shows how to use the new --start_stage, --end_stage, and --epochs_per_stage parameters

echo "========================================================================"
echo "Flexible Stage Training Examples"
echo "========================================================================"
echo ""
echo "The training code now supports flexible stage selection, allowing you to:"
echo "  1. Train specific stages independently"
echo "  2. Skip earlier stages and start from later ones"
echo "  3. Control the number of epochs per stage"
echo ""
echo "========================================================================"
echo ""

# Example 1: Test a single stage
echo "Example 1: Test only Stage 3 (Prototypical Learning)"
echo "------------------------------------------------------------------------"
echo "Command:"
echo "  python train.py --start_stage 3 --end_stage 3 --epochs 50 \\"
echo "    --batch_size 16 --backbone dinov2-vit-s --mixed_precision"
echo ""
echo "What happens:"
echo "  - Model stays in Stage 3 for all 50 epochs"
echo "  - Active losses: Classification + Contrastive + Prototypical"
echo "  - Useful for testing prototypical learning component"
echo ""

# Example 2: Test the final stage only
echo "Example 2: Test only Stage 4 (Full Model)"
echo "------------------------------------------------------------------------"
echo "Command:"
echo "  python train.py --start_stage 4 --end_stage 4 --epochs 100 \\"
echo "    --batch_size 32 --mixed_precision --early_stopping"
echo ""
echo "What happens:"
echo "  - Model stays in Stage 4 for all 100 epochs"
echo "  - All losses active from the start"
echo "  - Useful for testing the complete model without stage progression"
echo ""

# Example 3: Skip stage 1
echo "Example 3: Train Stages 2-4 (Skip Classification-Only Stage)"
echo "------------------------------------------------------------------------"
echo "Command:"
echo "  python train.py --start_stage 2 --end_stage 4 --epochs 75 \\"
echo "    --epochs_per_stage 25 --batch_size 32 --mixed_precision"
echo ""
echo "What happens:"
echo "  - Epochs 0-24:  Stage 2 (Classification + Contrastive)"
echo "  - Epochs 25-49: Stage 3 (+ Prototypical)"
echo "  - Epochs 50-74: Stage 4 (+ Domain Adversarial)"
echo "  - Useful when you want to start with contrastive learning"
echo ""

# Example 4: Focus on first two stages
echo "Example 4: Train Only Stages 1-2 (Basic Feature Learning)"
echo "------------------------------------------------------------------------"
echo "Command:"
echo "  python train.py --start_stage 1 --end_stage 2 --epochs 60 \\"
echo "    --epochs_per_stage 30 --batch_size 32 --mixed_precision"
echo ""
echo "What happens:"
echo "  - Epochs 0-29:  Stage 1 (Classification only)"
echo "  - Epochs 30-59: Stage 2 (Classification + Contrastive)"
echo "  - Useful for focusing on supervised and contrastive learning"
echo ""

# Example 5: Custom stage duration
echo "Example 5: All Stages with Custom Duration"
echo "------------------------------------------------------------------------"
echo "Command:"
echo "  python train.py --start_stage 1 --end_stage 4 \\"
echo "    --epochs_per_stage 30 --epochs 120 --batch_size 32"
echo ""
echo "What happens:"
echo "  - Epochs 0-29:   Stage 1"
echo "  - Epochs 30-59:  Stage 2"
echo "  - Epochs 60-89:  Stage 3"
echo "  - Epochs 90-119: Stage 4"
echo "  - Gives each stage more time to converge"
echo ""

# Example 6: Quick experimentation
echo "Example 6: Quick Stage Testing (5 epochs per stage)"
echo "------------------------------------------------------------------------"
echo "Command:"
echo "  python train.py --start_stage 1 --end_stage 4 \\"
echo "    --epochs_per_stage 5 --epochs 20 --batch_size 32"
echo ""
echo "What happens:"
echo "  - Epochs 0-4:   Stage 1"
echo "  - Epochs 5-9:   Stage 2"
echo "  - Epochs 10-14: Stage 3"
echo "  - Epochs 15-19: Stage 4"
echo "  - Useful for quick experimentation and debugging"
echo ""

echo "========================================================================"
echo "Additional Tips:"
echo "========================================================================"
echo ""
echo "1. Use config files for complex setups:"
echo "   python train.py --config config/my_experiment.yaml"
echo ""
echo "2. Combine with other options:"
echo "   - --resume_from checkpoints/checkpoint.pth"
echo "   - --exp_name my_experiment"
echo "   - --tensorboard"
echo "   - --early_stopping --patience 10"
echo ""
echo "3. Stage descriptions:"
echo "   Stage 1: Classification only"
echo "   Stage 2: + Contrastive learning (align paired classes)"
echo "   Stage 3: + Prototypical learning (handle unpaired classes)"
echo "   Stage 4: + Domain adversarial (domain invariance)"
echo ""
echo "4. To see all available options:"
echo "   python train.py --help"
echo ""
echo "========================================================================"
